### ISSUE TITLE
TypeError: 'ChampionGGStats' object is not subscriptable

### ISSUE THREAD

**Issue by dawyi** [meraki-analytics/cassiopeia-plugins#3]
when i try to run example code ( `lux.championgg[Role.middle].win_rate` ) i get this error:
`TypeError: 'ChampionGGStats' object is not subscriptable`
i am using python 3.6.1 Anaconda 4.4.0 64 bit - linux

**Comment by jjmaldonis** [comment]
Can you make sure that you're using the latest version of our championgg plugin from github (and not the latest one on pip). We'll make a new release on pip soon.
